os:
- linux

language: bash

before_install:
 - export TRAVIS_TAG="1.$TRAVIS_BUILD_NUMBER"
 - echo -n $TRAVIS_TAG > BADDLESHIP_VERSION

addons:
  #linux
  apt:
    packages:
      - desktop-file-utils
      - p7zip-full
  #osx
  homebrew:
    update: true
    packages:
      - dmd
      - dub
      - p7zip


script:
  #linux
  - >
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then 
      #don't use apt dmd because it uses GDC, we need DMD or LDC (GDC is broken with gtkd)
      curl -fsS https://dlang.org/install.sh | bash -s dmd;
      source ~/dlang/dmd-2.086.0/activate;
      dub build -b release --parallel --force --arch=x86_64
      7z a -tzip Baddleship-AppDir.zip assets Baddleship BADDLESHIP_VERSION &
      #cd tools/rpm && sh generate_rpm.sh && cd ../../ &
      #cd tools/flatpak && sh generate_flatpak.sh && cd ../../ &
      #cd tools/snap && sh generate_snap.sh && cd ../../ &
      # cd tools/deb && sh generate_deb.sh && cd ../../ &
      # cd tools/appimage && sh gtk.sh && cd ../../ &
      wait
    fi
  #windows
  # - >
  #   if [ "$TRAVIS_OS_NAME" == "windows" ]; 
  #     then wget http://downloads.dlang.org/nightlies/dmd-master/dmd.master.windows.7z;
  #     7z x dmd.master.windows.7z;
  #     git clone https://github.com/yatima1460/GTK3-Windows-32bit;
  #     dmd2/windows/bin/dub build -c CLI -b release --parallel --force --arch=x86;
  #     7z a -tzip Baddleship-CLI-Windows-x86.zip assets Baddleship-CLI.exe;
  #     dmd2/windows/bin/dub build -c GTK -b release --parallel --force --arch=x86;
  #     mv GTK3-Windows-32bit/*.dll .;
  #     7z a -tzip Baddleship-Windows-x86.zip assets Baddleship.exe BADDLESHIP_VERSION *.dll;
  #   fi
  #osx 
  #  - >
  #    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
  #      dub build -c CLI -b release --parallel --force --arch=x86_64;
  #      7z a -tzip Baddleship-CLI-OSX.zip assets Baddleship-CLI BADDLESHIP_VERSION;
  #      dub build -c GTK -b release --parallel --force --arch=x86_64;
  #      7z a -tzip Baddleship-OSX.zip assets Baddleship BADDLESHIP_VERSION;
  #    fi
  
before_deploy:
  # - test -f tools/appimage/Baddleship.AppImage
  # - test -f tools/deb/Baddleship.deb
  - test -f Baddleship-AppDir.zip
  # - test -f Baddleship-CLI-AppDir.zip
  # - test -f Baddleship-CLI-Windows-x86.zip
  # - test -f Baddleship-Windows-x86.zip

before_deploy:
 - git config --local user.name "RustyRaptor"
 - git config --local user.email "ziadarafat1@gmail.com"
 #- git tag "$TRAVIS_TAG" "$TRAVIS_COMMIT"

deploy:
  provider: releases
  skip_cleanup: true
  draft: false
  prerelease: true
  name: $TRAVIS_TAG
  body: Automated Travis build
  target_commitish: $TRAVIS_COMMIT
  api_key:
    secure: $GITHUB_TOKEN
  file: 
    # - tools/appimage/Baddleship.AppImage
    # - tools/deb/Baddleship.deb
    - Baddleship-AppDir.zip
    # - Baddleship-CLI-AppDir.zip
    # - Baddleship-CLI-Windows-x86.zip
    # - Baddleship-Windows-x86.zip
    
    #- tools/appimage/Baddleship-CLI.AppImage
    #- Baddleship-CLI-Windows.zip
    #- Baddleship-Windows.zip
    #- Baddleship-OSX.zip
    #- Baddleship-CLI-OSX.zip
    
    
  on:
    repo: RustyRaptor/Baddleship

notifications:
  email:
    on_success: always
    on_failure: always
